name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select branch to deploy"
        required: true
        default: "deploy-frontend"
        type: choice
        options:
          - adding-feature
          - main
          - deploy-frontend

jobs:

  deploy:
    name: Clone and Deploy Frontend
    runs-on: ubuntu-latest

    steps:

      # 1. Connect to EC2 and clone frontend using GitHub SSH
      - name: Clone and deploy frontend
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            set -e

            echo "Connected to EC2"

            # Go to project directory
            cd ~/my_project

            # Remove old frontend source
            rm -rf Ecommerce-frontend

            # Clone frontend from GitHub using SSH
            git clone -b ${{ inputs.environment }} \
              git@github.com:Priya2508-glitch/Ecommerce-frontend.git \
              Ecommerce-frontend

            # Go to frontend project
            cd Ecommerce-frontend

            # Install dependencies
            npm ci

            # Run lint if available
            npm run lint --if-present

            # Build React/Vite application
            npm run build

            # Remove old frontend files from Nginx
            rm -rf /var/www/ecommerce-frontend/*

            # Copy new build
            cp -r dist/* /var/www/ecommerce-frontend/

            # Set ownership
            chown -R www-data:www-data /var/www/ecommerce-frontend

            # Test Nginx configuration
            sudo nginx -t

            # Reload Nginx
            sudo systemctl reload nginx

            echo "Frontend deployment completed successfully"